### ISSUE TITLE
How to generate data.dists

### ISSUE THREAD

**Issue by Lemour-sudo** [working-yuhao/DEAL#3]
I am using the CiteSeer dataset that is in the repo and using the default settings.
However I get stuck at this point in _model.py_:

![dist-1](https://user-images.githubusercontent.com/36408408/108179885-cc89dd00-710e-11eb-83f5-b59534b4d382.PNG)

_data.dists_ cannot be subscripted since it is a _NoneType_.
May I ask how to generate this 'dists' and what it actually represents.

**Comment by Lemour-sudo** [comment]
I found the link to download the file in the "About dist data" file.
Thanks.

**Comment by mohitagarwal0212** [comment]
@Lemour-sudo hey, i had downloaded the data, were you able to figure out what it represents ?

**Comment by Lemour-sudo** [comment]
@mohitagarwal0212 I think it must represent the distances (or reciprocals of the distances) between each pair of nodes in the graph.
