### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rhythming** [working-yuhao/DEAL#8]
Device: using  cuda:0
theta_list:(0.1, 0.85, 0.05)
Namespace(BCE_mode=True, approximate=-1, attr_model='Emb', batch_size=8, cache=True, comment='0', cuda='0', dataset='CiteSeer', dropout=False, epoch_log=2, epoch_num=5000, feature_dim=64, gamma=2, gpu=True, hidden_dim=64, inductive=False, layer_num=2, loss='default', lr=0.01, output_dim=64, ps='', remove_link_ratio=0.2, repeat_num=1, res_dir=None, rm_feature=False, strong_A=False, task='link', train_mode='cos', train_ratio=0.1, use_order=False)
  0%|                                                                                                                              | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 117, in <module>
    loss = deal.default_loss(inputs, labels, data, thetas=theta_list, train_num=int(X_train.shape[0] *args.train_ratio)*2)
  File "/home/fn/zml/DEAL/DEAL-master/model.py", line 466, in default_loss
    dists = data.dists[nodes[:,0],nodes[:,1]] 
TypeError: 'NoneType' object is not subscriptable

I don't know why this is happening，Can you take a look at it for me？

**Comment by rhythming** [comment]
I had the same issue and the solution is to download the&nbsp;dists-1.dat&nbsp;file, as in data/CiteSeer/About dist data.
I created a fork to assist with the setup instructions (see Installation here&nbsp;https://github.com/lajd/DEAL/blob/master/README.md)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "working-yuhao/DEAL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月14日(星期四) 上午10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [working-yuhao/DEAL] TypeError: 'NoneType' object is not subscriptable (#8)





 
Hi @rhythming , I met the same issue, may I know how you solved it? thanks
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Wyz-8263** [comment]
Solved it, thanks!
